{{- if .Values.schedule }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "presidio-scout.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        {{- include "presidio-scout.podTemplate" . | nindent 8 }}
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "presidio-scout.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  template:
    {{- include "presidio-scout.podTemplate" . | nindent 4 }}
{{- end }}
